\documentclass[12pt]{article}

%%% PAGE DIMENSIONS
\usepackage{geometry}
\geometry{a4paper}
\geometry{margin=2cm}

%%% PACKAGES
\usepackage[authoryear]{natbib}
\bibliographystyle{besjournals}

\usepackage{makecell,booktabs}

\usepackage{setspace}
\doublespacing
% \linespread{1.25}

\usepackage{graphicx}

\usepackage{tabularx}
\usepackage{adjustbox}

\usepackage{multirow}

\usepackage[running]{lineno}

\usepackage{caption}
\captionsetup{justification=raggedright, singlelinecheck=false}
\usepackage[font=small,labelfont=bf,labelsep=space]{caption}

\usepackage{subcaption}
\captionsetup{justification=raggedright, singlelinecheck=false}
\usepackage[font=small,labelfont=bf,labelsep=space]{subcaption}

\usepackage{pgfplots}
\pgfplotsset{width=16cm}

\usepackage{authblk}

\usepackage{amsmath}

\usepackage{hyperref} % for \url

\usepackage{pdflscape} %for landscape table

\usepackage{afterpage} %for Table on next page

%%% HEADERS and FOOTERS
\usepackage{fancyhdr}
\pagestyle{fancy}
\renewcommand{\headrulewidth}{0pt}
\lhead{}\chead{}\rhead{}
\lfoot{}\cfoot{\thepage}\rfoot{}

%%% SECTION TITLE APPEARANCE
\usepackage{sectsty}
\setcounter{secnumdepth}{-1}
\subsectionfont{\normalfont\fontsize{14}{15}\selectfont}
\DeclareMathSizes{10}{11}{9}{7}

%%% DEFINE NEW COMMANDS
\newcommand{\B}{\textbf}
\newcommand{\TL}{\textless}
\newcommand{\PRZ}{\text{Pr}\bigl( >\mid Z \mid \bigr)}
\newcommand{\head}[1]{\textnormal{\textbf{#1}}}

\newenvironment{nscenter}
 {\parskip=.75pt\par\nopagebreak\centering}
 {\par\noindent\ignorespacesafterend}

\makeatletter
\renewcommand{\fnum@figure}{Fig. \thefigure.}
\renewcommand{\fnum@table}{Table \thetable.}
\makeatother

\newcommand{\fillcaption}[1]{ %new command with the argument being the text of the caption
\textbf{Fig. \arabic{figure}:} #1 %Makes main figure number, concatenates it to legend
\addtocounter {figure} {1} %increments main figure count
}

%% FOR SUPPLEMENT SETTINGS
\newcommand{\beginsupplement}{%
        \setcounter{table}{0}
        \renewcommand{\thetable}{S\arabic{table}}%
        \setcounter{figure}{0}
        \renewcommand{\thefigure}{S\arabic{figure}}%
     }

\begin{document}
\linenumbers

%%% DOCUMENT CONTENT
\title{Decoupling plant economics traits and biomass carbon composition in wetland litter \\ \huge Supplemental Material}
\author[*ab]{S. M. Windecker}
\author[b]{S. M. Trevathan-Tackett}
\author[a]{N. Golding}
\author[acd]{J. A. Catford}
\author[b]{P. I. Macreadie}
\author[a]{P. A. Vesk}

\affil[a]{School of BioSciences, University of Melbourne, Parkville VIC 3010, Australia}
\affil[b]{Centre for Integrative Ecology, School of Life and Environmental Sciences, Deakin University, Burwood Campus, Burwood VIC 3125, Australia}
\affil[c]{Biological Sciences, University of Southampton, Highfield Campus, Southampton SO17 1BJ, UK}
\affil[d]{Fenner School of Environment and Society, Australian National University, Canberra ACT 2601, Australia}
\affil[*]{Corresponding author: sm.windecker@unimelb.edu.au}
\date{}
\maketitle

\pgfplotsset{width=16cm}

\begin{figure}[!ht]
	\scalebox{0.5}
	{\includegraphics{figs/fs_simulate.png}}
	\caption{Parametric study of the Fraser-Suzuki function for deconvolution of derivative thermogravimetric biomass curves: (a) Effect of modifying height; (b) skew; (c) position; and (d) width.}
	\label{Fig:fs_simulation}
\end{figure}

\afterpage{%
	\clearpage%
	\thispagestyle{empty}
	\begin{landscape}%
	\centering
		\begin{table}[!htbp]
		\caption{Fraser-Suzuki mixture model parameter estimates for each species.}
		\label{Tab:parameters}
		\begin{adjustbox}{width=1.5\textwidth}
		\begin{tabular}{l r r r r r r r r r r r r r r r r}
		\toprule
		\multicolumn{1}{c}{} & \multicolumn{4}{l}{Height} & \multicolumn{4}{l}{Position} & \multicolumn{4}{l}{Skew} & \multicolumn{4}{l}{Width}\\
		\cmidrule(lr){2-5}
		\cmidrule(lr){6-9}
		\cmidrule(lr){10-13}
		\cmidrule(lr){14-17}
		Species & HC-1 & HC-2 & CL & LG & HC-1 & HC-2 & CL & LG & HC-1 & HC-2 & CL & LG & HC-1 & HC-2 & CL & LG \\
		\midrule
		\input{figs/tga_param_table.tex}
		\bottomrule
		\end{tabular}
		\end{adjustbox}
	\end{table}
\end{landscape}
\clearpage
}

\begin{table}[ht] \centering
	\caption{GenBank Accession codes.}
	\label{Tab:genbank}
	\begin{tabular}{l l l}
	\toprule
		Species & rbcl & matK \\
		\midrule
		\input{figs/gen_bank_accessions.tex}
		\bottomrule
	\end{tabular}
\end{table}

\afterpage{%
	\clearpage%
	\thispagestyle{empty}
	\begin{landscape}%
	\centering
	\begin{figure}
	\scalebox{0.4}
	{\includegraphics{figs/phylo_all.png}}
	\caption{Phylogenetic tree of species with traits. Tree at genus level where species level sequences for rcbL gene unavailable. If the branch represents more than one species, the trait value was averaged among species in that genus.}
	\label{Fig:phylo}
\end{figure}
\end{landscape}
\clearpage
}

\begin{table}[ht]
  \centering
	\caption{Mantel test for the correlation between branch length distance and functional trait distances between the seven traits.}
	\label{Tab:mantel}
	\begin{tabular}{l r r}
	\toprule
		Trait & Mantel Test observation & $P$-value \\
		\midrule
		\input{figs/mantel_results.tex}
		\bottomrule
	\end{tabular}
\end{table}

\begin{figure}[!ht]
	\scalebox{0.3}
	{\includegraphics{figs/pairplot.png}}
	\caption{Correlations between traits. Size of $R^2$ listed on bottom panel proportional to weight of relationship, with star to indicate significance at P \textless 0.05.}
	\label{Fig:pairplot}
\end{figure}

\begin{figure}[!ht]
\centering
	\begin{subfigure}[ht]{0.9\textwidth}
		\includegraphics[width=\textwidth]{figs/tga_ar.png}
		\subcaption{DTG deconvolution for amphibious fluctuation-responders (n = 5).}
		\label{Fig:tga_ar}
	\end{subfigure}\hfill
\end{figure}
\begin{figure}[!ht]\ContinuedFloat
	\begin{subfigure}[ht]{0.9\textwidth}
		\includegraphics[width=\textwidth]{figs/tga_at.png}
		\subcaption{DTG deconvolution for amphibious fluctuation-tolerators (n = 11).}
		\label{Fig:tga_at}
	\end{subfigure}\hfill
\end{figure}
\begin{figure}[!ht]\ContinuedFloat
	\begin{subfigure}[ht]{0.9\textwidth}
		\includegraphics[width=\textwidth]{figs/tga_tda.png}
		\subcaption{DTG deconvolution for terrestrial damp species (n = 8).}
		\label{Fig:tga_tda}
	\end{subfigure}\hfill
\end{figure}
\begin{figure}[!ht]\ContinuedFloat
	\begin{subfigure}[ht]{0.9\textwidth}
		\includegraphics[width=\textwidth]{figs/tga_tdr.png}
		\subcaption{DTG deconvolution for terrestrial dry species (n = 5).}
		\label{Fig:tga_tdr}
	\end{subfigure}
	\caption{All species first derivative thermogravimetric (DTG) deconvolutions: (a) amphibious fluctuation-responders; (b) amphibious fluctuation-tolerators; (c) terrestrial damp species; and (d) terrestrial dry species.}
	\label{Fig:tga_all}
\end{figure}

\begin{table}[!htbp]\centering
	\caption{Principal Component Analysis axis loadings.}
	\label{Tab:pca}
	\begin{tabular}{l r r r r}
        		\toprule
        		Trait & Axis 1 & Axis 2 \\
        		\midrule
		\input{figs/pca_loadings.tex}
        		\bottomrule
	\end{tabular}
\end{table}

\afterpage{%
	\clearpage%
	\thispagestyle{empty}
	\begin{landscape}%
	\centering
\begin{table}[ht]
	\caption{Hierarchical classification scheme of wetland plant species by habit and response to water. Devised by Brock and Casanova (1997).}
	\label{Tab:fxl_groups}
	\centering
	\small
	\begin{tabularx}{\textwidth}{lllX}
        		\toprule
        		Abbreviation & Primary category & Secondary category & Description \\
        		\midrule
		AR & Amphibious & Fluctuation-responders & Species which germinate in flooded conditions, grow in both flooded and damp conditions, and reproduce above the surface of the water. \\
		AT & Amphibious & Fluctuation-tolerators & Species which germinate in damp or flooded conditions and tolerate variation in water level. \\
		Tda & Terrestrial & Damp species & Species which germinate, grow, and reproduce on saturated soil. \\
		Tdr & Terrestrial & Dry species & Species which germinate, grow, and reproduce where there is no surface water and water table is below the soil surface. \\
        		\bottomrule
	\end{tabularx}
\end{table}
\end{landscape}
\clearpage
}

\begin{figure}
	\centering
	\scalebox{0.3}
	{\includegraphics{figs/tga_pure_samples.png}}
	\caption{Predicted negative derivative thermogravimetric for raw biomass samples: (a) carboxy-methyl cellulose; (b) alkali lignin.}
	\label{Fig:tga_pure}
\end{figure}


\end{document}