\begin{table}[ht]
	\caption{Hierarchical classification scheme of wetland plant species by habit and response to water. Devised by Brock and Casanova (1997).}
	\label{apx:fxl_groups}
	\centering
	\small
	\begin{tabularx}{\textwidth}{lllX}
        		\toprule
        		Abbreviation & Primary category & Secondary category & Description \\
        		\midrule
		AR & Amphibious & Fluctuation-responders & Species that germinate in flooded conditions, grow in both flooded and damp conditions, and reproduce above the surface of the water. \\
		AT & Amphibious & Fluctuation-tolerators & Species that germinate in damp or flooded conditions and tolerate variation in water level. \\
		Tda & Terrestrial & Damp species & Species that germinate, grow, and reproduce on saturated soil. \\
		Tdr & Terrestrial & Dry species & Species that germinate, grow, and reproduce where there is no surface water and water table is below the soil surface. \\
        		\bottomrule
	\end{tabularx}
\end{table}

\begin{table}[ht] \centering
	\caption{GenBank Accession codes.}
	\label{apx:genbank}
	\begin{tabular}{l l l}
	\toprule
		Species & rbcl & matK \\
		\midrule
		\input{chapters/Chapter3_traits/figs/gen_bank_accessions.tex}
		\bottomrule
	\end{tabular}
\end{table}

\begin{figure}[ht]
	\scalebox{0.5}
	{\includegraphics{chapters/Chapter3_traits/figs/fs_simulate.png}}
	\caption{Parametric study of the Fraser-Suzuki function for deconvolution of derivative thermogravimetric biomass curves: (a) Effect of modifying height; (b) skew; (c) position; and (d) width.}
	\label{apx:fs_simulation}
\end{figure}

\begin{figure}[ht]
	\includegraphics[width=\textwidth]{chapters/Chapter3_traits/figs/tga_ar.png}
	\caption{First derivative thermogravimetric (DTG) deconvolution for amphibious fluctuation-responders (AR; n = 5).}
	\label{apx:tga_ar}
\end{figure}

\begin{figure}[ht]
	\includegraphics[width=\textwidth]{chapters/Chapter3_traits/figs/tga_at.png}
	\caption{First derivative thermogravimetric (DTG) deconvolution for amphibious fluctuation-tolerators (AT; n = 11).}
	\label{apx:tga_at}
\end{figure}

\begin{figure}[ht]
	\includegraphics[width=\textwidth]{chapters/Chapter3_traits/figs/tga_tda.png}
	\caption{First derivative thermogravimetric (DTG) deconvolution for terrestrial damp species (Tda; n = 8).}
	\label{apx:tga_tda}
\end{figure}

\begin{figure}[ht]
	\includegraphics[width=\textwidth]{chapters/Chapter3_traits/figs/tga_tdr.png}
	\caption{First derivative thermogravimetric (DTG) deconvolution for terrestrial dry species (Tdr; n = 5).}
	\label{apx:tga_tdr}
\end{figure}

\begin{figure}
	\centering
	\scalebox{0.3}
	{\includegraphics{chapters/Chapter3_traits/figs/tga_pure_samples.png}}
	\caption{Predicted negative derivative thermogravimetric for raw biomass samples: (a) carboxy-methyl cellulose; (b) alkali lignin.}
	\label{apx:tga_pure}
\end{figure}

\begin{landscape}%
	\centering
		\begin{table}[htbp]
		\caption{Fraser-Suzuki mixture model parameter estimates for each species.}
		\label{apx:parameters}
		\begin{adjustbox}{width=1.5\textwidth}
		\begin{tabular}{l r r r r r r r r r r r r r r r r}
		\toprule
		\multicolumn{1}{c}{} & \multicolumn{4}{l}{Height} & \multicolumn{4}{l}{Position} & \multicolumn{4}{l}{Skew} & \multicolumn{4}{l}{Width}\\
		\cmidrule(lr){2-5}
		\cmidrule(lr){6-9}
		\cmidrule(lr){10-13}
		\cmidrule(lr){14-17}
		Species & HC-1 & HC-2 & CL & LG & HC-1 & HC-2 & CL & LG & HC-1 & HC-2 & CL & LG & HC-1 & HC-2 & CL & LG \\
		\midrule
		\input{chapters/Chapter3_traits/figs/tga_param_table.tex}
		\bottomrule
		\end{tabular}
		\end{adjustbox}
	\end{table}
\end{landscape}

\begin{table}[ht]
  \centering
	\caption{Mantel test for the correlation between branch length distance and functional trait distances between the seven traits. Litter area per mass is bold to indicate significant correlation.}
	\label{apx:mantel}
	\begin{tabular}{l r r}
	\toprule
		Trait & Mantel Test observation & $P$-value \\
		\midrule
		\input{chapters/Chapter3_traits/figs/mantel_results.tex}
		\bottomrule
	\end{tabular}
\end{table}

\begin{table}[!htbp]\centering
	\caption{Principal Component Analysis axis loadings.}
	\label{apx:pca}
	\begin{tabular}{l r r r r}
        		\toprule
        		Trait & Axis 1 & Axis 2 \\
        		\midrule
		\input{chapters/Chapter3_traits/figs/pca_loadings.tex}
        		\bottomrule
	\end{tabular}
\end{table}

\begin{landscape}%
	\centering
	\begin{figure}
	\scalebox{0.4}
	{\includegraphics{chapters/Chapter3_traits/figs/phylo_all.png}}
	\caption{Phylogenetic tree of species with traits. Tree at genus level where species level sequences for rcbL gene unavailable. If the branch represents more than one species, the trait value was averaged among species in that genus.}
	\label{apx:phylo}
\end{figure}
\end{landscape}

\begin{figure}[!ht]
	\scalebox{0.3}
	{\includegraphics{chapters/Chapter3_traits/figs/pairplot.png}}
	\caption{Correlations between traits. Size of $R^2$ listed on bottom panel proportional to weight of relationship, with star to indicate significance at P \textless 0.05.}
	\label{apx:pairplot}
\end{figure}
