---
title: "Traits"
author: "SW"
date: "6/27/2017"
output:
    pdf_document:
        includes:
            in_header: header.tex
---

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 50)
```


\blandscape
```{r load, echo = FALSE, warning = FALSE}
# packages
library(latex2exp) 
library(knitr)
library(kableExtra)
library(xtable)
library(pander)
library(reshape2)

# set working directory path
wd <- '/Users/windeckers/Dropbox/projects/THESIS.bioassay/'

# source pairplot function code
source(paste0(wd, 'R/pairPlot.R'))
```

``` {r pairplot, echo = FALSE, fig.width=12, fig.height=8}
# report this centred already??
# show GAM lines here? 

n <- read.table(paste0(wd, 'munge/inundated_data.txt'))
names <- c('species', 'species_code', 'mgC', 'mgN', 'mSLA', 'mLDMC', 'mg_p1', 'mg_p2', 'mg_p3', 'gf')

# remove phrag and M for now until have final trait values for them.
sptrt <- unique(n[!(n$species_code == 'S' | n$species_code == 'M'),names])

scale_st <- sptrt
for (i in 3:9) {
  scale_st[i] <- scale(scale_st[i])
}

# df only traits
traits <- c('mSLA', 'mLDMC', 'mgN', 'mgC', 'mg_p1', 'mg_p2', 'mg_p3')
pp <- sptrt[,traits]

# set up colnames for table
labels <- c(TeX('Specific leaf area (cm^2 g^{-1})'), TeX('Leaf dry matter content (mg g^{-1})'), TeX('Leaf Nitrogen content (mg g^{-1})'), TeX('Leaf Carbon content (mg g^{-1})'), TeX('Leaf hemicellulose content (mg g^{-1})'), TeX('Leaf cellulose content (mg g^{-1})'), TeX('Leaf lignin content (mg g^{-1})'))

# png(paste0(wd, 'output/figures_for_paper/pairplot.png'), 8, 8, 'in', res = 100)
pairs(pp, labels = labels, upper.panel = panel.cor)
# dev.off()
```

\newpage
``` {r table, echo = FALSE, results = 'asis', comment = ""}
## add family designations and number of samples to species names)
family <- read.csv(paste0(wd, 'raw/species_family.csv'))

sptab <- merge(sptrt[, names(sptrt) != 'species'], family[,c('species_code', 'species', 'family')])
sptab <- sptab[, c('family', 'species', 'mSLA', 'mLDMC', 'mgN', 'mgC', 'mg_p1', 'mg_p2', 'mg_p3')]
sptab <- sptab[order(as.character(sptab$species)),]

model_parameters <- read.table(paste0(wd, 'munge/nest_model_parameters.txt'), header = TRUE)
model_parameters$species <- gsub('_',' ', model_parameters$species)
model_parameters <- dcast(model_parameters, species ~ term, value.var = 'estimate')

sptab <- merge(sptab, model_parameters)

colnames(sptab) <- c('Family', 'Species', 'Specific leaf area\n(cm^2 g^{-1})', '$Leaf dry matter content\n(mg g^{-1})$', 'Leaf Nitrogen content\n$(mg g^{-1})$', 'Leaf Carbon content\n$(mg g^{-1})$', 'Leaf hemicellulose content\n$(mg g^{-1})$', 'Leaf cellulose content\n$(mg g^{-1})$', 'Leaf lignin content\n$(mg g^{-1})$', 'alpha', 'beta', 'k')

write.csv(sptab, paste0(wd, 'output/speciestraits_parameters.csv'), row.names = FALSE)
# this worked for kable
# sptab$species <- paste0("\\textit{", sptab$species, "}")
emphasize.italics.cols(2)

pandoc.table(sptab, keep.line.breaks = TRUE, justify = 'left')


```
pandoc test.txt -o test.pdf

\elandscape
\newpage
```{r PCA, echo = FALSE, warning = FALSE}

pp2<- pp
for (i in colnames(pp2)) {
  pp2[i] <- log(pp2[i])
}

pp_sub <- pp2[, c('mSLA', 'mg_p2', 'mg_p1')]
n.pca <- prcomp(pp_sub, scale. = TRUE)
print(n.pca)
plot(n.pca, type = 'l')
summary(n.pca)

```

``` {r PCA visual, echo = FALSE, warning = FALSE}

# library(devtools)
# install_github("ggbiplot", "vqv/ggbiplot")
# library(ggbiplot)
# #png("output/pca_by_gf.png", units="in", width=5, height=4, res=200)
# g <- ggbiplot(n.pca, obs.scale = 1, var.scale = 1,
#               groups = sptrt$gf, ellipse = TRUE,
#               circle = TRUE) +
#   scale_color_discrete(name = '')+
#   theme(legend.direction = 'horizontal', legend.position = 'top')
# print(g)
#dev.off()
```

\newpage
``` {r pca 2, echo = FALSE}
# # PCA WITH TRAINING
# # split data into 2 parts for pca training (75%) and prediction (25%)
# set.seed(1)
# samp <- sample(nrow(n), nrow(n)*0.75)
# n.train <- n[samp,]
# n.valid <- n[-samp,]
#
# # conduct PCA on training dataset
# pca <- prcomp(n.train[, which(colnames(n) %in% covariates)], retx=TRUE, center=TRUE, scale=TRUE)
# expl.var <- round(pca$sdev^2/sum(pca$sdev^2)*100) # percent explained variance
#
# # prediction of PCs for validation dataset
# pred <- predict(pca, newdata=n.valid[, which(colnames(n) %in% covariates)])
# pc <- c(1,2) # principal components to plot
#
# v.pred <- as.data.frame(pred)

# VISUAL DISPLAY 3
# ###Plot result
# COLOR <- c(2:4)
# PCH <- c(1,16)
#
# png("output/pca_with_training.png", units="in", width=5, height=4, res=200)
# op <- par(mar=c(4,4,1,1), ps=10)
# plot(pca$x[,pc], col=COLOR[n.train$gf], cex=PCH[1],
#      xlab=paste0("PC ", pc[1], " (", expl.var[pc[1]], "%)"),
#      ylab=paste0("PC ", pc[2], " (", expl.var[pc[2]], "%)")
# )
# points(pred[,pc], col=COLOR[n.valid$gf], pch=PCH[2])
# legend("topright", legend=levels(n$gf), fill = COLOR, border = COLOR)
# legend("topleft", legend=c("training data", "validation data"), col=1, pch=PCH)
# par(op)
# dev.off()


# PCA approach 3
#################################################################################
# Sandra script

#################### PCA on 6 traits #####################################
# select the traits
#pp2 <- pp[,c('mLDMC', 'mg_p2', 'mg_p3')]
cov2 <- scale(pp, center = T, scale = T)

# use princomp for PCA for being consistent with scaling of scores in Sandra's analysis
prin <- princomp((cov2), cor = TRUE, scores = TRUE)
pc12 <- prin$scores[,1:2]
ll <- prin$loadings


################ KERNEL DENSITY ESTIMATION ##############################
library(vegan)
library(ks)

H <- Hpi(x=pc12)      # optimal bandwidth estimation
est<- kde(x=pc12, H=H, compute.cont=TRUE)     # kernel density estimation

# set contour probabilities for drawing contour levels
cl<-contourLevels(est, prob=c(0.5, 0.05, 0.001), approx=TRUE)

fit<-envfit(pc12, cov2) # use envfit for drawing arrows, can be also done using trait loadings
fit2<-fit$vectors$arrows*-1 # drawing line segments in arrow opposites direction for pretty layout

fit2<-fit$vectors$arrows*-1
#  not sure why these numbers.....
# fit2[1,]<-fit2[1,]*4.5
# fit2[2,]<-fit2[2,]*5.5
# fit2[3,]<-fit2[3,]*4.2

par(mar=c(4,4,2,2))
plot(est, cont=seq(1,100,by=1), display="filled.contour2", add=FALSE, ylab="", xlab="",
     cex.axis=0.75, ylim=c(-6, 5), xlim=c(-5, 5),las=1)
plot(est,abs.cont=cl[1], labels=c(0.5),labcex=0.75, add=TRUE, lwd=0.75, col="grey30")
plot(est,abs.cont=cl[2], labels=c(0.95),labcex=0.75, add=TRUE, lwd=0.5, col="grey60")
plot(est,abs.cont=cl[3], labels=c(0.99),labcex=0.75, add=TRUE, lwd=0.5, col="grey60")
points( pc12[,], pch=16, cex=0.25, col="black")
plot(fit, cex=0.90, col=1, labels=list(vectors = c('SLA', 'LDMC', 'LN', 'LC', 'HC', 'CL', 'LG')))
segments(0,0, fit2[,1], fit2[,2], col=1, lty=2, lwd=1)
mtext("PC1", cex=0.75, side=1, line=0.5, adj=1)
mtext("PC2", cex=0.75, side=2, line=0.5, at=4.7) #, las=2)


```

\newpage
``` {r echo = FALSE}
# library(reshape2)
# st_long <- melt(sptrt, id.vars = c('species', 'species_code', 'gf'))
# scale_long <- melt(scale_st, id.vars = c('species', 'species_code', 'gf'))
# 
# write.table(scale_long, paste0(wd, 'munge/scale_long.txt'), row.names = FALSE)
# 
# st_c <- st_long[st_long$variable == 'mg_p1' |st_long$variable == 'mg_p2' |st_long$variable == 'mg_p3' ,]
# 
# p <- ggplot(st_c, aes(gf, value)) + 
#   geom_boxplot()
# p + facet_wrap(~ variable)



```



